{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "form137-api.fullname" . }}-secret
  labels:
    {{- include "form137-api.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URI: {{ .Values.secret.data.MONGO_URI | default (.Values.app.mongodb.uri | b64enc) | quote }}
{{- end }}