spring:
  data:
    mongodb:
      database: demo-dev   # logical DB name inside embedded server
  servlet:
    multipart:
      enabled: false  # Disable multipart support completely
server:
  port: 8080
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.5
auth:
  enabled: false
kafka:
  enabled: false  # Disable Kafka for local development
