apiVersion: apps/v1
kind: Deployment
metadata:
  name: form137-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: form137-api
  template:
    metadata:
      labels:
        app: form137-api
    spec:
      containers:
        - name: form137-api
          image: jasoncalalang/form137-api-requestor:1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: form137-cm
                  key: SPRING_DATA_MONGODB_DATABASE
            - name: AUTH0_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: form137-cm
                  key: AUTH0_ISSUER_URI

            - name: AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: form137-cm
                  key: AUTH0_AUDIENCE
